### PR TITLE
Fix an issue with Multiple Response answer

### PR DESCRIPTION
**Pull request by Basil-Ross**
Fix for an issue with Multiple Response answer

### CODE REVIEW

**Comment by Basil-Ross** [comment]
If an iSpring quiz has a Multiple Response question with the setting "Score by choice", there is an error in script logs:
`{"ts":"2022-09-01 16:58:24","request_parameters":"array (\n  0 => \n  LibXMLError::__set_state(array(\n     'level' => 2,\n     'code' => 1866,\n     'column' => 0,\n     'message' => 'Element \\'{http:\/\/www.ispringsolutions.com\/ispring\/quizbuilder\/quizresults}answer\\', attribute \\'score\\': The attribute \\'score\\' is not allowed.\n',\n     'file' => '\/home\/f0704399\/domains\/f0704399.xsph.ru\/public_html\/',\n     'line' => 1,\n  )),\n)","ts_":1662040704},`

In this case, a user's answer breakdown becomes empty.

If in **Quiz Report.xsd**  we add the 'score' attribute, the report will be generated as expected.

**Comment by Basil-Ross** [comment]
I have also fixed an issue when equation tools corrupt quiz results.

**Comment by alexey-malov** [comment]
We are reviewing this Pull Request and examine whether it corresponds to quiz player code base

**Comment by alexey-malov** [comment]
We have update QuizReport XML schema with another Pull request. It should resolve the problem

**Pull request closed without merging**
